### ISSUE TITLE
Server Crash on ghast griefing

### ISSUE THREAD

**Issue by CritFlaw** [GeheimagentNr1/MoreMobGriefingOptions#1]
**Versions**
Minecraft Version: [e.g. 1.16.5]
1.16.5
Minecraft Forge Version: [e.g. 36.1.4]
36.1.12
Mod Version: [e.g. 1.0.0]
2.0.0
**Log files**
Please append the log, debug-log and if available the crash-log files.
https://pastebin.com/9HuSHyMP
**Describe the bug**
Happened when a ghast tried to shoot fire charges. I'm not sure why it happened this time, because they've done it before and been fine. It happened in the overworld in a Quark lava lake thing.

**To Reproduce**
Steps to reproduce the behaviour:
Like I said above, not really sure. All I know is ghast fire blasts caused it in my case.

**Expected behaviour**
To not crash :)

**Screenshots**
N/A

**Additional context**
Nope

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Investigations running</td></tr><tr><th>Issue type:</th><td>Critical Bug</td></tr><tr><th>Fix type:</th><td>tba.</td></tr><tr><th>Fix version:</th><td>tba</td></tr><tr><th>Fix release date:</th><td>tba</td></tr></tbody></table>

**Issue confirmed for:**

No version

**TODOs:**

*   [ ] Investigating for a longer period than a few minutes
*   [ ] Investigate if there is an issue with the mobs of Quark

**Comment by GeheimagentNr1** [comment]
Are you playing on a multi or a single player world?

**Comment by CritFlaw** [comment]
A theory I have, I'm using the forge version of immersive portals, and the lava lake I have, has a very large area of obsidian from water bucketing the area. I'm wondering if the ghast explosion is somehow interacting with immersive portals, trying to create a far too large portal. It may also be why ghasts and pigmen are spawning there for no apparent reason

**Comment by Darkere** [comment]
https://github.com/GeheimagentNr1/MoreMobGriefingOptions/blob/e86f7c02b5e44f8fae5e9a677f6bb4943f35c39c/src/main/java/de/geheimagentnr1/moremobgriefingoptions/config/ServerConfig.java#L31

wrong Registry. Use `ForgeRegistries.Entity`

**Comment by glentakahashi** [comment]
Similar crash when killing a wither for some reason. Might be because the wither was spawned inside a claimed chunk

**Comment by GeheimagentNr1** [comment]
Please test, if this Snapshot fixes the problem. (The jar is in the zip file, because jar-files can not be attached to issue comments.)

In this version mob griefing event without a valid entity (if the entity is null) will be ignored and the vanilla mob griefing game rule will be used.

[MoreMobGriefingOptions-1.16.5-2.0.1-SNAPSHOT.zip](https://github.com/GeheimagentNr1/MoreMobGriefingOptions/files/6527945/MoreMobGriefingOptions-1.16.5-2.0.1-SNAPSHOT.zip)

**Comment by GeheimagentNr1** [comment]
Due to the lack of response, I assume that the version provided fixed the bug.
The fix was just released as version 2.0.1 on CurseForge.
Changelog: https://github.com/GeheimagentNr1/MoreMobGriefingOptions/wiki/Changelog-2.0.1
Download: https://www.curseforge.com/minecraft/mc-mods/more-mobgriefing-options/files/all
